In [4]:
import numpy as np
import cv2
import scipy
import scipy.ndimage
import os

In [9]:
image = cv2.imread(os.path.join("/Users/Indix/Downloads/amazon_captcha/processed/", "7.jpg"))
print len(image)

70


In [71]:
cv2.imwrite(os.path.join("/Users/Indix/Downloads/amazon_captcha/processed/", "1.jpg") ,image[20:50])                   

True

In [76]:
print image[37][60:80]

[[255 255 255]
 [251 251 251]
 [255 255 255]
 [255 255 255]
 [  0   0   0]
 [  1   1   1]
 [  1   1   1]
 [  2   2   2]
 [  1   1   1]
 [  0   0   0]
 [  0   0   0]
 [  1   1   1]
 [  0   0   0]
 [  2   2   2]
 [  0   0   0]
 [  0   0   0]
 [255 255 255]
 [255 255 255]
 [253 253 253]
 [253 253 253]]


166